name: ci
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/chainguard-dev/apko:sha256-d5543aa8349d18a0d6a884a0bc9935625d9620df021210be26e1e9ca038b414e.sig # apko-0.22
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log the step container node version
        uses: docker://ghcr.io/chainguard-dev/apko:sha256-d5543aa8349d18a0d6a884a0bc9935625d9620df021210be26e1e9ca038b414e.sig
        with:
          entrypoint: apko
          args: -v
